area:
  center:
    lat: -41.17883162579788
    lng: 174.82355117797854
  size: # in meters
    width: 2048
    height: 2048
heightmap:
  resolution: 1.00 # meters per pixel
base_texture:
  resolution: 0.25 # meters per pixel
